### ISSUE TITLE
All APIs that return just success/error with possibly human-readable messages should use same response schema

### ISSUE THREAD

**Issue by rambo** [pvarki/python-rasenmaeher-api#36]
https://github.com/pvarki/python-libpvarki/blob/main/src/libpvarki/schemas/generic.py#L8 should cover these use cases.

Things that need to return machine-readable extra information of course need their own schemas.

https://github.com/pvarki/docker-rasenmaeher-integration/actions/runs/6126663424/job/16631101326?pr=16#step:9:86 demonstrates a problem with ad-hoc schemas.

**Comment by karppo** [comment]
Default schema was added to those I found using about same response schema.
