### ISSUE TITLE
Get Enduserpfx returns http error 500

### ISSUE THREAD

**Issue by aarne33** [pvarki/python-rasenmaeher-api#57]
[enduserpfx-500-rmlocal-rmapi-1.logs.txt](https://github.com/pvarki/python-rasenmaeher-api/files/12761726/enduserpfx-500-rmlocal-rmapi-1.logs.txt)

In high level these api calls were done in the attached log:

firstuser/add-admin
invitecode/create
invitecode/?invitecode
invitecode/enroll
enrollment/list
enrollment/have-i-been-accepted
enrollment/accept
enrollment/have-i-been-accepted
enduserpfx/<callsign>

**Comment by rambo** [comment]
Fixed by https://github.com/pvarki/python-rasenmaeher-api/pull/58
